services:
  mysql:
    image: mysql:8.0
    container_name: newsapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: NativeNewsDB
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: newsapp-backend
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=NativeNewsDB
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: newsapp-frontend
    ports:
      - "19000-19002:19000-19002"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mysql-data: